load_module modules/ngx_http_js_module.so;

events {}

http {
    js_import badge from /opt/www/icon-badge/nginx/badge.js;

    server {
        listen 80;
        server_name badge.beauhou.cn;

        root /opt/www/icon-badge;
        index index.html;

        # Root:
        #   https://badge.beauhou.cn/                       -> index.html
        #   https://badge.beauhou.cn?key=Lang&value=Java17&bg=green
        location = / {
            js_content badge.indexOrBadge;
        }

        location = /badge.svg {
            js_content badge.badge;
        }

        location = /icon-badge.svg {
            js_content badge.badge;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
